# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6946baf7a2b6580ba18fc466ef8845c85302f06e4703fa057be35e872d310fcac09e067982bc8e82bc6eb6d51c16530ab7f0126aa6f1b844606ec7fb825ea789

test:
  secret_key_base: 7441e48c9a6bef3be98927bc6d613b983088108fdacdafc7cacd3cd6ad56385a9511bbd1177f11c62b5b56ec74837e92971c02f104ad3f3a028c138a9d968d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
